wad_dashboard/app/mod_waddashboard/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, session, redirect, url_for, Markup

try:
    from app.mod_auth.controllers import login_required
    from app.libs import html_elements
    from app.libs import libgroups, libdisplay
    from app.libs.shared import dbio_connect, INIFILE
    from .models import WDMainGroups, WDSections, WDSubGroups, WDMainItems, WDUserGroups, WDUsers, WDSubItems
except ImportError:
    from wad_dashboard.app.mod_auth.controllers import login_required
    from wad_dashboard.app.libs import html_elements
    from wad_dashboard.app.libs import libgroups, libdisplay
    from wad_dashboard.app.libs.shared import dbio_connect, INIFILE
    from wad_dashboard.app.mod_waddashboard.models import WDMainGroups, WDSections, WDSubGroups, WDMainItems, WDUserGroups, WDUsers, WDSubItems

import datetime
from dateutil.relativedelta import relativedelta

# logging
from werkzeug.local import LocalProxy
from flask import current_app
logger = LocalProxy(lambda: current_app.logger)

dbio = dbio_connect()
    
# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_blueprint = Blueprint('waddashboard', __name__, url_prefix='/waddashboard')

def get_visible_groups():
    """
    returns a list of visible MainGroups for the currently logged in user
    """
    if session.get('logged_in'):
        role = session.get('role')
        user = WDUsers.get_by_id(session.get('user_id'))
    else:
        return []
    if role>0:
        usergroups = [ug.maingroup for ug in WDUserGroups.select().where(WDUserGroups.user == user) ]
    else:  
        usergroups = WDMainGroups.select().order_by(WDMainGroups.name)

    return usergroups

def is_maingroup_visible(maingroup):
    """
    maingroup is a WDMainGroups instance
    """
    return maingroup in get_visible_groups()

def is_subgroup_visible(subgroup):
    """
    subgroup is a WDSubGroups instance
    """
    if session.get('logged_in'):
        role = session.get('role')
        if role == 0:
            return True

    for group in get_visible_groups():
        for sg in WDMainItems.select().where(WDMainItems.maingroup == group):
            if subgroup == sg.subgroup:
                return True

    return False

def is_selector_visible(selector):
    """
    selector is a DBSelectors instance
    """
    if session.get('logged_in'):
        role = session.get('role')
        if role == 0:
            return True

    for group in get_visible_groups():
        for sg in WDMainItems.select().where(WDMainItems.maingroup == group):
            for sel in WDSubItems.select().where(WDSubItems.subgroup == sg.subgroup):
                if selector == sel.selector:
                    return True

    return False

# Set the route and accepted methods
@mod_blueprint.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    """
    Just present a menu with choices; should all be require authorization
    """

    usergroups = get_visible_groups()

    menustoprow = []
    menus = [
    ]
    
    totalmenu=[
        { 'label':'QC dashboard', 'href':url_for('.qc') }, 
    ]

    role = 2
    if session.get('logged_in'):
        role = session.get('role')
    if role == 0:
        totalmenu.append(
            { 'label':'All active selectors', 'href':url_for('.qc', all_selectors=1) }
        )   

    menustoprow.append({'title':'Overview', 'items':totalmenu})
    for section in WDSections.select().order_by(WDSections.position):
        title = section.name
        vizgroups = section.maingroups.order_by(WDMainGroups.name)

        selection = []
        for gr in vizgroups:
            if gr in usergroups:
                selection.append(gr)
        if len(selection) == 0:
            continue
        vizgroups = selection

        items = [ {'label':i.name , 'href':url_for('.qc', group=i.name),
                   'subitems': [{'label': si.subgroup.name, 'href':url_for('.qc',group=i.name, subgroup=si.subgroup.name)} 
                                for si in WDMainItems.select().join(WDSubGroups).where(WDMainItems.maingroup == i).order_by(WDSubGroups.name) ] } 
                  for i in vizgroups ]

        menus.append({'title':title, 'items':items})
        
    return render_template('waddashboard/home.html', menus=menus, menustoprow=menustoprow, title='WAD-QC Dashboard')

def show_this_qc(latest_date, production, latest_status, filters):
    """
    return True or False for filter selected
    """
    # no filters, must show
    if len(filters) == 0:
        return True

    # determine each status and the worst as well
    do_show = True
    worst = -1
    status = {}
    for key,elem in [('date',latest_date), ('production',production), ('status',latest_status)]:
        try:
            if '<div style="background-color:{}"'.format(libdisplay.COLOR_CRITICAL) in elem:
                status[key] = 2
            elif '<div style="background-color:{}"'.format(libdisplay.COLOR_WARNING) in elem:
                status[key] = 1
            elif '<div style="background-color:{}"'.format(libdisplay.COLOR_OK) in elem:
                status[key] = 0
        except TypeError:
            status[key] = 0 # assume 'good' for any elem without a color (status)
            
        worst = max(worst, status[key])
        if status[key] >= filters.get(key, -1):
            do_show = do_show & True
        else:
            do_show = False

    # if 'any' defined, then report only worst
    if 'any' in filters.keys():
        if worst >= filters['any']:
            return True
        else:
            return False
    
    return do_show 
            
@mod_blueprint.route('/qc')
@login_required
def qc():
    # show a table with selectors:
    #   name, description, latest acq date (red/green), latest qc status (red/green), status production (red/green)

    usergroups = get_visible_groups()

    msg=''
    _group = request.args.get('group', None)
    _subgroup = request.args.get('subgroup', None)
    _separate = 1 if 'separate' in request.args else None
    _all_selectors = (str(request.args.get('all_selectors', None)) == "1")
    role = 2
    if session.get('logged_in'):
        role = session.get('role')
    if role > 0 and _all_selectors: # only for admin
        _all_selectors = False

    filters = {}
    possible_filters = ['date', 'status', 'production', 'any']
    for key in possible_filters:
        if key in request.args:
            try:
                filters[key] = int(request.args[key])
            except:
                pass
    if filters.get('any',-1)> -1: # remove all other filters
        filters = {'any':filters['any']}

    add_refresh = int(request.args.get('refresh', session.get('refresh')))
    
    # status of processes
    num_status = {}
    nprocs = 0
    
    results = []
    subgroups = []
    if not _subgroup is None:
        grps = [ sg.maingroup for sg in WDMainItems.select().join(WDSubGroups).where(WDSubGroups.name == _subgroup) ]
        for grp in grps:
            if grp in usergroups:
                subgroups = [_subgroup]
                break

    elif not _group is None:
        if WDMainGroups.get_by_name(_group) in usergroups:
            subgroups = sorted([ sg.subgroup.name for sg in WDMainItems.select().join(WDMainGroups).where(WDMainGroups.name == _group) ])
    else:
        # subgroup is None, group is None
        subgroups = set()
        for group in usergroups:
            for sg in WDMainItems.select().where(WDMainItems.maingroup == group):
                subgroups.add( sg.subgroup.name )
        subgroups = sorted(list(subgroups))
        
    if _all_selectors:
        res, stu = groupoverview(filters, None, None, True) 
        results.extend(res)
    
        # find number of jobs still in processes table
        procs = dbio.DBProcesses.select().where(dbio.DBProcesses.selector << stu)
        for data in procs:
            if not data.process_status.name in num_status:
                num_status[data.process_status.name] = 0
            num_status[data.process_status.name] += 1
        nprocs += len(procs)
    else:    
        for sub in subgroups:
            res, stu = groupoverview(filters, _group, sub, not (_separate is None)) 
            results.extend(res)
    
            # find number of jobs still in processes table
            procs = dbio.DBProcesses.select().where(dbio.DBProcesses.selector << stu)
            for data in procs:
                if not data.process_status.name in num_status:
                    num_status[data.process_status.name] = 0
                num_status[data.process_status.name] += 1
            nprocs += len(procs)
        
    msg = 'Number of processes still in the queue: {}'.format(nprocs)
    if nprocs>0:
        for key,val in num_status.items():
            msg += "\n\t{}: {}".format(key,val)
    
    table_rows = []
    for res in results:
        table_rows.append(res)

    table = html_elements.Table(headers=['name', 'description', 'latest date', 'latest status', 'production 6m'],
                                rows=table_rows,
                                _class='tablesorter-wadred', _id='sortTable')

    # add some status pickers
    stat_vals = [
        ('', -1),
        ('ok', 0),
        ('warning', 1),
        ('critical', 2)
    ]
    pickers = Markup()
    for fil in possible_filters:
        # make a dropdown selector
        linkopt = {'refresh': add_refresh}
        if _all_selectors:
            linkopt['all_selectors']=1
        if _separate:
            linkopt['separate']=1
            
        if not _group is None and not _subgroup is None:
            link = '"{}"'.format(url_for('.qc', group=_group, subgroup=_subgroup, **linkopt))
        elif not _group is None:
            link = '"{}"'.format(url_for('.qc', group=_group, **linkopt))
        elif not _subgroup is None:
            link = '"{}"'.format(url_for('.qc', subgroup=_subgroup, **linkopt))

wad_dashboard/app/templates/layout.html
{% from "macros.html" import nav_link with context %}
{% from "macros.html" import toggle_login_link with context %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WAD-QC Dashboard</title>
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='bootstrap-submenu.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='sticky-footer-navbar.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='tablesorter/theme.wadred.css') }}" rel="stylesheet" media="screen">
    {% if witheditor %}
    <link href="{{ url_for('static', filename='jsoneditoronline/jsoneditor.min.css') }}" rel="stylesheet" type="text/css">
    {% endif %}
    <link href="{{ url_for('static', filename='collapsiblelist/clist.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='wad2.css') }}" rel="stylesheet" media="screen">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <!-- Placed at the end of the document will make pages load faster, but also redraw table on slow machines -->
  <script src="{{ url_for('static', filename='jquery-3.3.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='tablesorter/jquery.tablesorter.min.js') }}"></script>
  <script src="{{ url_for('static', filename='tablesorter/jquery.tablesorter.widgets.min.js') }}"></script>
  <script src="{{ url_for('static', filename='collapsiblelist/CollapsibleLists.js') }}"></script>
  {% if witheditor %}
  <script src="{{ url_for('static', filename='jsoneditoronline/jsoneditor.min.js') }}"></script>
  {% endif %}
  {% block refreshpage %}{% endblock %}
  <script>
  $(document).ready(function(){
    {% if numtables %}
    {% for i in range(numtables) %}
    $("#sortTable{{ i }}").tablesorter({widgets:['zebra', 'filter']});
    {% endfor %}
    {% else %}
    $("#sortTable").tablesorter({widgets:['zebra', 'filter']});
    $("#sortTable2").tablesorter({widgets:['zebra', 'filter']});
    {% endif %}
    CollapsibleLists.apply();
    {% if add_refresh is defined %}
    checkReloading();
    {% endif %}
  });
  </script>

  </head>
  <body>
    <header>
      <!-- Fixed navbar -->
     <nav class="navbar navbar-expand-md navbar-dark fixed-top wad-nav-dashboard-bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('waddashboard.home') }}">WAD-QC Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{{ url_for('admin.default') }}" id="navbarDropdownMenuLink">
                Admin
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                 <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Grouping</a>
                   <ul class="dropdown-menu">
                     <li><a class="dropdown-item" href="{{ url_for('admin.sections') }}">Sections</a></li>
                     <li><a class="dropdown-item" href="{{ url_for('admin.groups') }}">MainGroups</a></li>
                     <li><a class="dropdown-item" href="{{ url_for('admin.subgroups') }}">SubGroups</a></li>
                   </ul>
                 </li>
                 <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Display</a>
                   <ul class="dropdown-menu">
                     <li><a class="dropdown-item" href="{{ url_for('display.default') }}">Results</a></li>
                     <li><a class="dropdown-item" href="{{ url_for('admin.usergroups') }}">UserGroups</a></li>
                   </ul>
                 </li>
                 <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Resources</a>
                   <ul class="dropdown-menu">
                     <li><a class="dropdown-item" href="{{ url_for('auth_users.default') }}">User Management</a></li>
                     <li><a class="dropdown-item" href="{{ url_for('admin.licenses') }}">Licenses</a></li>
                   </ul>
                 </li>
              </ul>
             </li>
          {{ nav_link('waddashboard.qc', 'Dashboard') }}
          </ul>
          <ul class="navbar-nav navbar-right">
            {{ toggle_login_link('auth.signin', 'Log in', 'auth.logout', 'Log out') }}
          </ul>
        </div>
      </div>
     </nav>
    </header>

    <!-- Begin page content -->
    <div class="container-fluid">
        <main class="col" role="main">
        <br>
        {% block content %}{% endblock %}
        <br>
        </main>
    </div>

    <footer class="footer wad-nav-dashboard-bg-dark">
      <div class="container-fluid">
        <span class="float-left">Copyright © 2016</span>
        <span class="float-right"><img src="{{ url_for('static', filename='nvkf-logo-60-white.gif') }}" alt="NVKF" height="60" width="60"><a class="wad-brand-link" href="https://www.nvkf.nl">NVKF</a></span>
     </div>
    </footer>
  </body>
</html>

wad_dashboard/app/templates/macros.html
{% macro nav_link(endpoint, name) %}
{% if request.endpoint.endswith(endpoint) %}
    <li class="nav-item  active"><a class="nav-link" href="{{ url_for(endpoint) }}">{{name}}</a></li>
{% else %}
    <li class="nav-item"><a class="nav-link" href="{{ url_for(endpoint) }}">{{name}}</a></li>
{% endif %}
{% endmacro %}

{% macro toggle_login_link(endpoint_login, label_login, endpoint_logout, label_logout) %}
{% if session.get('logged_in') %}
    <li class="nav-item" style="background-color:red; padding-top:7px; padding-bottom:7px; padding-left:10px; padding-right:10px">{{ session.get('rolename').strip() }}</li><li class="nav-item"><a class="nav-link" href="{{ url_for(endpoint_logout) }}">{{label_logout}}</a></li>
{% else %}
    <li class="nav-item"><a class="nav-link" href="{{ url_for(endpoint_login) }}">{{label_login}}</a></li>
{% endif %}
{% endmacro %}