wad_admin/app/mod_wadconfig/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
     flash, session, redirect, url_for, Markup

try:
    from app.mod_auth.controllers import login_required
    from app.libs.shared import INIFILE, dbio_connect
    from app.libs import html_elements
    from app.libs.modulerepos import check_releases
    import wadservices_communicate as wad_com

except ImportError:
    from wad_admin.app.mod_auth.controllers import login_required
    from wad_admin.app.libs.shared import INIFILE, dbio_connect
    from wad_admin.app.libs import html_elements
    from wad_admin.app.libs.modulerepos import check_releases
    import wad_admin.wadservices_communicate as wad_com

dbio = dbio_connect() 

import time

# logging
from werkzeug.local import LocalProxy
from flask import current_app
logger = LocalProxy(lambda: current_app.logger)

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_blueprint = Blueprint('wadconfig', __name__, url_prefix='/wadadmin')

# Set the route and accepted methods
@mod_blueprint.route('/home/', methods=['GET', 'POST'])
@login_required
def home():
    """
    Just present a menu with choices; should all be require authorization
    """
    menus = [
    ]
    resourcesmenu=[
        { 'label':'server status', 'href':url_for('wadconfig.whatsup') }, #'whatsup'
        { 'label':'data sources', 'href':url_for('wadconfig_sources.default') },
        { 'label':'tags for selector rules', 'href':url_for('wadconfig_ruletags.default') },
        { 'label':'WAD Processor', 'href':url_for('wadconfig_wadprocessor.default', gid=1) }, 
        { 'label':'WAD-QC database', 'href':url_for('wadconfig_dbtool.default') }, 
        { 'label':'User manager', 'href':url_for('auth_users.default') }, 
        { 'label':'Licenses', 'href':url_for('wadconfig.licenses') },
    ]

    configmenu=[
        { 'label':'factory modules', 'href':url_for('wadconfig_factorymodules.default') }, 
        { 'label':'import modules', 'href':url_for('wadconfig_importexport.importing', gid=1) }, 
        { 'label':'export modules', 'href':url_for('wadconfig_importexport.exporting', gid=1) }, 
        { 'label':'backup selectors', 'href':url_for('wadconfig_backuprestore.backingup', gid=1) }, 
        { 'label':'restore selectors', 'href':url_for('wadconfig_backuprestore.restoring', gid=1) }, 
        { 'label':'selectors', 'href':url_for('wadconfig_selectors.default') }, 
    ]


    processmenu=[
        { 'label':'processes', 'href':url_for('wadconfig_processes.default') },
        { 'label':'results', 'href':url_for('wadconfig_results.default') }, 
    ]

    advancedmenu=[
        { 'label':'analysis modules', 'href':url_for('wadconfig_modules.default') },
        { 'label':'module configs',  'href':url_for('wadconfig_configs.default') }, 
        { 'label':'meta configs',  'href':url_for('wadconfig_metas.default') }, 
    ]

    menus.append({'title':'Resources', 'items':resourcesmenu})
    menus.append({'title':'Configuration', 'items':configmenu})
    menus.append({'title':'Processes/Results', 'items':processmenu})
    menus.append({'title':'Advanced', 'items':advancedmenu})
    return render_template("wadconfig/home.html", menus=menus, title='WAD-QC Server Administration')


@mod_blueprint.route('/licenses/')
@login_required
def licenses():
    # show the licenses of the various pieces of software included

    link = html_elements.Link(label="Flask", href="http://flask.pocoo.org/", target="_blank")
    subtitle = "WAD-Admin is a {} app, and makes use of these additional pieces of open source software.".format(link)

    table_rows = []
    table_rows.append(["Bootstrap", 
                       html_elements.Link(label="https://getbootstrap.com/", href="https://getbootstrap.com/", target="_blank"), 
                       html_elements.Link(label="MIT", href=url_for('static', filename='licenses/bootstrap/LICENSE.txt'))])

    table_rows.append(["tablesorter",
                       html_elements.Link(label="https://mottie.github.io/tablesorter/", href="https://mottie.github.io/tablesorter/", target="_blank"), 
                       html_elements.Link(label="MIT", href=url_for('static', filename='licenses/tablesorter/LICENSE.txt'))])

    table_rows.append(["JSON Editor Online", 
                       html_elements.Link(label="http://jsoneditoronline.org/", href="http://jsoneditoronline.org/", target="_blank"), 
                       html_elements.Link(label="Apache License 2.0", href=url_for('static', filename='licenses/jsoneditoronline/LICENSE.txt'))])


    table = html_elements.Table(headers=['Component', 'URL', 'License'], rows=table_rows)
    return render_template("wadconfig/generic.html", title='Licenses', subtitle=Markup(subtitle), html=Markup(table))

@mod_blueprint.route('/whatsup/')
@login_required
def whatsup():
    # show the status of several services
    result = []

    wp_start = html_elements.Button(label='start', href=url_for('.wadcontrol', command='start'))
    wp_pause = html_elements.Button(label='pause', href=url_for('.wadcontrol', command='pause'))
    wp_quit  = html_elements.Button(label='quit', href=url_for('.wadcontrol', command='quit'))

    ort_start = html_elements.Button(label='start', href=url_for('.orthanc', command='start'))
    ort_restart = html_elements.Button(label='restart', href=url_for('.orthanc', command='restart'))
    ort_quit = html_elements.Button(label='quit', href=url_for('.orthanc', command='quit'))

    # psql_start = html_elements.Button(label='start', href=url_for('.pgcontrol', command='start')) # should be running else wadadmin would be down
    psql_reload = html_elements.Button(label='reload', href=url_for('.pgcontrol', command='reload'))
    # psql_quit = html_elements.Button(label='quit', href=url_for('.pgcontrol', command='stop')) # quit will bring wadamin down

    wap_restart = html_elements.Button(label='restart', href=url_for('.sitecontrol', command='restart', service='wadapi'))
    wap_quit = html_elements.Button(label='quit', href=url_for('.sitecontrol', command='stop', service='wadapi'))
    wap_start = html_elements.Button(label='start', href=url_for('.sitecontrol', command='start', service='wadapi'))

    wab_restart = html_elements.Button(label='restart', href=url_for('.sitecontrol', command='restart', service='waddashboard'))
    wab_quit = html_elements.Button(label='quit', href=url_for('.sitecontrol', command='stop', service='waddashboard'))
    wab_start = html_elements.Button(label='start', href=url_for('.sitecontrol', command='start', service='waddashboard'))

    services = [ # process name, identifier on cmdline
                 {'name': 'postgresql', 'process':'postgresql', 'buttons':['', psql_reload]}, # at least for the Orthanc database
                 {'name': 'orthanc', 'process':'Orthanc', 'buttons':[ort_start, ort_restart, ort_quit]}, # preferred PACS solution 
                 {'name': 'wadprocessor', 'process':'wadprocessor', 'buttons':[wp_start, wp_pause, wp_quit]}, # wad_qc processor
                 {'name': 'wadadmin', 'process':'wadadmin', 'buttons':[]}, # wadadmin has no controls
                 {'name': 'wadapi', 'process':'wadapi', 'buttons':[wap_start, wap_restart, wap_quit]}, # wadapi
                 {'name': 'waddashboard', 'process':'waddashboard', 'buttons':[wab_start, wab_restart, wab_quit]}, # waddashboard
                 ]    

    systemd_services = {'orthanc': 'wadorthanc', 'postgresql': 'wadpostgresql', 'wadprocessor': 'wadprocessor'}
    apache2_services = {'wadadmin': 'wadadmin', 'waddashboard': 'waddashboard', 'wadapi': 'wadapi'}

    # set service status to NOT RUNNING
    for service in services:
        status = is_service_running(service['process'])
        if service['name'] in systemd_services.keys():
            systemd = wad_com.controlled_by_systemd(systemd_services[service['name']])
            if systemd:
                result.append({
                    "label": "{} (controlled by systemd)".format(service['name']),
                    "cell": {'value':status[0], 'style': status[1]}, 
                    "buttons": []
                })
            else:
                result.append({
                    "label": service['name'],
                    "cell": {'value':status[0], 'style':status[1]},
                    "buttons":service['buttons']
                })

        if service['name'] in apache2_services.keys():
            if wad_com.controlled_by_apache2(wad_com.get_apache2_name(apache2_services[service['name']])):
                result.append({
                    "label": "{} (controlled by apache2)".format(service['name']),
                    "cell": {'value':status[0], 'style':status[1]}, 
                    "buttons": []
                })
            elif wad_com.controlled_by_nginx(wad_com.get_nginx_name(apache2_services[service['name']])):
                result.append({
                    "label": "{} (controlled by nginx/systemd)".format(service['name']),
                    "cell": {'value':status[0], 'style':status[1]}, 
                    "buttons": []
                })
            else:
                result.append({
                    "label": service['name'],
                    "cell": {'value':status[0], 'style':status[1]},
                    "buttons": service['buttons']
                })

    table_rows = []
    for res in result:
        row = [res['label'], res['cell']]
        row.extend(res['buttons'])
        table_rows.append(row)
    table = html_elements.Table(headers=['Service',   'Status'], rows=table_rows)

    # versions
    hdr2 = html_elements.Heading(label="Versions", type="h2")
    col_ok   = {'bgcolor':'yellowgreen'}
    col_bad =  {'bgcolor':'Red'}

    version_db   = dbio.DBVariables.get(dbio.DBVariables.name == 'iqc_db_version').val
    version_dbio = dbio.__version__
    import pkg_resources
    version_whl = pkg_resources.get_distribution("wad_qc").version
    
    results2 = []

wad_admin/app/templates/layout.html
{% from "macros.html" import nav_link with context %}
{% from "macros.html" import toggle_login_link with context %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WAD-QC Admin</title>
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='sticky-footer-navbar.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='tablesorter/theme.wadred.css') }}" rel="stylesheet" media="screen">
    {% if witheditor %}
    <link href="{{ url_for('static', filename='jsoneditoronline/jsoneditor.min.css') }}" rel="stylesheet" type="text/css">
    {% endif %}
    <link href="{{ url_for('static', filename='wad2.css') }}" rel="stylesheet" media="screen">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <!-- Placed at the end of the document will make pages load faster, but also redraw table on slow machines -->
  <script src="{{ url_for('static', filename='jquery-3.3.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='tablesorter/jquery.tablesorter.min.js') }}"></script>
  <script src="{{ url_for('static', filename='tablesorter/jquery.tablesorter.widgets.min.js') }}"></script>
  {% if witheditor %}
  <script src="{{ url_for('static', filename='jsoneditoronline/jsoneditor.min.js') }}"></script>
  {% endif %}
  {% block refreshpage %}{% endblock %}
  <script>
  $(document).ready(function(){
    $("#sortTable").tablesorter({widgets:['zebra', 'filter']});
    $("#sortTableNoFilter").tablesorter({widgets:['zebra']});
    {% if add_refresh is defined %}
    checkReloading();
    {% endif %}
  });
  </script>
  </head>
  <body>
    <header>
      <!-- Fixed navbar -->
     <nav class="navbar navbar-expand-md navbar-dark fixed-top wad-nav-admin-bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('wadconfig.home') }}">WAD-QC Admin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
          {{ nav_link('wadconfig_selectors.default', 'Selectors') }}
          {{ nav_link('wadconfig_processes.default', 'Processes') }}
          {{ nav_link('wadconfig_results.default', 'Results') }}
          {{ nav_link('wadconfig_dbtool.default', 'DBTool') }}
          {{ nav_link('wadconfig_dbtool.residuals', 'Residuals') }}
          </ul>
          <ul class="navbar-nav navbar-right">
            {{ toggle_login_link('auth.signin', 'Log in', 'auth.logout', 'Log out') }}
          </ul>
        </div>
      </div>
     </nav>
    </header>

    <!-- Begin page content -->
    <div class="container-fluid">
        <main class="col" role="main">
        <br>
        {% block content %}{% endblock %}
        <br>
        </main>
    </div>

    <footer class="footer wad-nav-admin-bg-dark">
      <div class="container-fluid">
        <span class="float-left">Copyright © 2016</span>
        <span class="float-right"><img src="{{ url_for('static', filename='nvkf-logo-60-white.gif') }}" alt="NVKF" height="60" width="60"><a class="wad-brand-link" href="https://www.nvkf.nl">NVKF</a></span>
     </div>
    </footer>
  </body>
</html>

wad_admin/app/templates/macros.html
{% macro nav_link(endpoint, name) %}
{% if request.endpoint.endswith(endpoint) %}
    <li class="nav-item active"><a class="nav-link" href="{{ url_for(endpoint) }}">{{name}}</a></li>
{% else %}
    <li class="nav-item"><a class="nav-link" href="{{ url_for(endpoint) }}">{{name}}</a></li>
{% endif %}
{% endmacro %}

{% macro toggle_login_link(endpoint_login, label_login, endpoint_logout, label_logout) %}
{% if session.get('logged_in') %}
    <li class="nav-item"><a class="nav-link" href="{{ url_for(endpoint_logout) }}">{{label_logout}}</a></li>
{% else %}
    <li class="nav-item"><a class="nav-link" href="{{ url_for(endpoint_login) }}">{{label_login}}</a></li>
{% endif %}
{% endmacro %}